baseURL = "https://genvira.com/"
languageCode = "en-us"
title = "Genvira"
theme="hugo-universal-theme"
font_size = "20px"
relativeURLs = true

[menu]

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="about-us"
    name = "About Us"
    url  = "/about-us"
    weight = 2

[[menu.main]]
    identifier="services"
    name = "Services"
    url  = "/services"
    weight = 3

[[menu.main]]
    identifier="research"
    name = "Research"
    url  = "/research"
    weight = 4

[[menu.main]]
    identifier="career"
    name = "Career"
    url  = "/career"
    weight = 5

[Params]
    
    style = "blue"

    logo = "img/logo/logo.png"
    logo_small = "img/logo/logo_small.png"
    
    banner = "img/banners/banner-cells-blue.jpg"
    
    # Footer information
    
    address = """310 Hunt Club Road East, 3rd Floor, Ottawa,
        <br> ON K1V 1C1, Canada
        <br> Tel: (613) 695-4718
        <br>
        """
    
    copyright = "© Genvira 2020"
    
    about_us = "Specialists in viral vector engineering for cancer immunotherapy, gene therapy, and vaccines."
    
[Params.carousel]
    enable = false
    
[Params.features]
    enable = false